spring.application.name=Escribasmostachos
server.port=8080

# Define app language
spring.web.locale=en
spring.web.locale-resolver=fixed

# Logs
logging.level.com.escribasmostachos=DEBUG

# JWT
jwt.secret=${JWT_SECRET}

# DataBase
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# hibernate logs
logging.level.org.hibernate.SQL=DEBUG

# Application properties
escribasmostachos.configuration.max-number-of-current-reads=2

# Internal hasing
hashid.salt=${HASH_SALT}